config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'teams#index'

  resources :teams do
    resources :heros
  end

  resources :heros

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :team

  validates :complexity, numericality: { less_than: 4 }
  validates :complexity, numericality: { greater_than: 0 }
  validates :complexity, numericality: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :heros
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :authenticate_user!

  def index
    @heros = Hero.all
  end

  def show
    @hero = Hero.find(params[:id])
  end

  def edit
    # if current_user == admin
    @hero = Hero.find(params[:id])
  end

  def new
    @hero = Hero.new
  end

  def create
    @hero = Hero.create!(hero_params)

    redirect_to heros_path
    flash[:notice] = "Created #{@hero.name}!"
  end

  def update
    # if current_user == admin
    @hero = Hero.find(params[:id])
    @hero.update!(hero_params)

    redirect_to hero_path
    flash[:notice] = "Updated #{@hero.name}!"
  end

private
  def hero_params
    params.require(:hero).permit(:name, :primary, :image, :complexity, :description, :playing, :with, :against, :team_id)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @heros = @team.heros
    @unpicked = Team.find_by_name(name = "unpicked")
    @dire = Team.find_by_name(name = "Dire")
    @radiant = Team.find_by_name(name = "Radiant")
  end

  def edit
    @team = Team.find(params[:id])
    @heros = Hero.all
  end

  def update
    @team = Team.find(params[:id])
    @team.update!(team_params)
  end

private
  def team_params
    params.require(:team).permit(@team.heros)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/heros/_form.html.erb
<%= form_for @hero, html: {class: "form-control wrapper-4"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.label :primary %>
  <%= f.select :primary, [ ["Strength", "str"], ["Agility", "agi"], ["Intelligence", 'int'] ] %>

  <%= f.label :team_id %>
  <%= f.collection_select(:team_id, Team.all, :id, :name) %>

  <%= f.label :complexity %>
  <%= f.select :complexity, options_for_select(1..3) %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :playing %>
  <%= f.text_area :playing %>

  <%= f.label :with %>
  <%= f.text_area :with %>

  <%= f.label :against %>
  <%= f.text_area :against %>

  <%= f.submit "Submit", :class => "btn" %>
<% end %>

app/views/heros/edit.html.erb
<%= @hero.name %>
<img src="<%= @hero.image %>" alt="<%= @hero.name %> Profile">

<%= render "form" %>

<%= link_to "Cancel", hero_path %>

app/views/heros/index.html.erb
<h3>All Heroes</h3>
<p>
  <%= link_to "Home", teams_path %> | 
  <%= link_to "Create Hero", new_hero_path %>
</p>
<div class="hero-pool">

  <% @heros.each do |hero| %>
  <a href="heros/<%= hero.id %>">
    <div class="hero">
      <img src="<%= hero.image %>">
    </div>
      <p class="hide show"><%= hero.name %></p>
  </a>
  <% end %>

</div>

app/views/heros/new.html.erb
<h3>New Hero</h3>

<%= link_to "Back To Heroes", heros_path %>
  <%= render 'form' %>
<%= link_to "Cancel", heros_path %>

app/views/heros/show.html.erb
<p>
  <%= link_to "Heroes", heros_path %> | <%= link_to "Edit", edit_hero_path %>
</p>
<h3><%= @hero.name %></h3>
<div class="wrapper-2">
  <div class="hero-profile">
<!-- show more info about hero and link to admin only edit -->
  <img src="<%= @hero.image %>">
</div>
  <div class="area-2">
    <ul>
      <li>Primary Attribute:
        <% if @hero.primary == "str" %>
          Strength
        <% elsif @hero.primary == "agi" %>
          Agility
        <% else %>
          Intelligence
        <% end %>
      </li>
      <li>Complexity:
        <% if @hero.complexity.to_i == 1 %>
          Normal
        <% elsif @hero.complexity.to_i == 2 %>
          Intermediate
        <% else %>
          Advanced
        <% end %>
      </li>
      <li> About:
        <%= @hero.description %>
      </li>
      <hr>
      <p>*Remember DOTA is a situational game, there is no one all ecompassing way to play any hero.</p>
      <li> Tips for Playing:
        <%= @hero.playing %>
      </li>
      <li> On Your Team:
        <%= @hero.with %>
      </li>
      <li> Playing Against:
        <%= @hero.against %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D2H</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/app/assets/stylesheets/application_2.css">
    <link rel="stylesheet" href="/app/assets/stylesheets/application.css">
  </head>
  <body>
    <% if !current_user %>
    | <%= link_to "Sign Up", new_user_registration_path %> |
    <%= link_to "Sign In", new_user_session_path %> |
    <% else %>
    | Welcome, <%= current_user.email %> |
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete%> |
    <% end %>
    <nav>
      <div class="title-div">
        <h1 class="title">DOTA</h1>
        <img src="https://krabo.ru/image/cache/data/game/D/DOTA_2/2014_01_23_11_32_40_697_38803_7703_Dota_2_Fyves20131119_2_1sdc326_0-140x140.png" alt="DOTA 2 LOGO" class="logo">
        <h1 class="title">HUB</h1>
      </div>
    </nav>
    <div class="area">
      <p class="alert"><%= flash[:alert] %></p>
      <p class="notice"><%= flash[:notice] %></p>
      <%= yield %>
    </div>
    <footer>
      <a href="#" class="kla">kla</a>
    </footer>
  </body>
</html>